sudo: false
language: rust
rust:
- 1.22.0  # Two releases back
- stable
- beta
- nightly
matrix:
  include:
  - name: check rustfmt
    rust: 1.38.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add rustfmt
    script:
      - cargo fmt --all -- --check
  - name: check with -D warnings
    env: RUSTFLAGS="-D warnings"
    rust: 1.38.0  # `stable`: Locking down for consistent behavior
    script:
    - cargo check --tests --all-features
  - name: check clippy
    rust: 1.38.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add clippy
    script:
      - cargo clippy --all --all-features -- -D warnings

install:
- rustc -Vv
- cargo -V
- export PATH=$HOME/.cargo/bin:$PATH

script:
- cargo check --verbose
- cargo check --verbose --no-default-features
- cargo check --verbose --all-features
- cargo test  --verbose --all-features

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
